### ISSUE TITLE
DCS-BIOS not detected and/or initial setup hang workaround

### ISSUE THREAD

**Issue by knightelessar** [51st-Vfw/DCSWaypointEditor#10]
For v1.0.0-raven_BETA.6, DCS-BIOS may not be detected, and the program auto-install may result in an initial setup hang.

The workaround is as follows:

1. On top of a manual DCS-BIOS install, create version text for DCS BIOS version check
Create or edit `Saved Games\DCS\Scripts\DCS-BIOS\release_version.txt` to have one line:
`0.7.40`
2. Open the `dcs_wp_editor\dcs_wp_editor.exe` to do initial setup
2.a If the program hangs or the DCS-BIOS install is not successful:
Force quit the program. Then, verify or rename the `Saved Games\DCS\Scripts\DCS-BIOS.bak` folder back into `DCS-BIOS`
3. In `dcs_wp_editor\settings.ini`
3.a Change default air frame to one of the following:
hornet, harrier, mirage, tomcat, warthog, viper
3.b Verify or edit the `path_dcs` to your `Saved Games` folder path

Example `settings.ini`:
```
[PREFERENCES]
path_dcs = E:\knigh\Saved Games\DCS\
path_tesseract = C:\Program Files\Tesseract-OCR\tesseract.exe
path_mission = C:\Users\knigh\Desktop\dcs_mission.xml
dcs_grace_period = 4
dcs_btn_rel_delay_short = 0.15
dcs_btn_rel_delay_medium = 0.30
hotkey_capture = ctrl+t
hotkey_capture_mode = ctrl+shift+t
hotkey_enter_profile = ctrl+alt+t
hotkey_enter_mission = ctrl+alt+shift+t
airframe_default = hornet
callsign_default = Colt1-1
is_auto_upd_check = true
is_tesseract_debug = false
profile_db_name = profiles.db

```
4. Open `dcs_wp_editor.exe`

**Comment by knightelessar** [comment]
The DCS-BIOS mentioned above is available as the DCS-BIOS_0.7.40.zip
 in assets below:
https://github.com/DCSFlightpanels/dcs-bios/releases/tag/0.7.40

**Comment by ilominar** [comment]
Tracking down cause of installation corruption that leads to need for the workaround.

**Comment by ilominar** [comment]
Original source of installation issues should be fixed in B7.

**Comment by knightelessar** [comment]
Hang is fixed by graceful error messages in B7.
