### ISSUE TITLE
F10 waypoint feature not working, only error noise.

### ISSUE THREAD

**Issue by Snake1263** [51st-Vfw/DCSWaypointEditor#25]
I believe I did everything correct on the install since all other features work well but the F10 coordinate puller only makes an error noise when I press the hotkey. I am using precise lat long (DD MM SS.ss) and I checked that the screenshot folder gets the correct screenshots but no coordinates come up on the display.

**Comment by ilominar** [comment]
Could you attach your log file following an attempt to capture coordinates? The log file is "log.txt" from the installation directory (same directory that has "dcs_wp_editor.exe").

**Comment by Snake1263** [comment]
The problem was an FPS counter at the top right corner. Solved.
