### ISSUE TITLE
F18 MSN Waypoints entering in meters in Feet field.

### ISSUE THREAD

**Issue by CaptainBandages** [51st-Vfw/DCSWaypointEditor#26]
F18 MSN Waypoints entering in meters in Feet field.

**Comment by ilominar** [comment]
I'm not seeing this? Can you provide more information to replicate?

Ran the following test and it looks (to me, though I might be misunderstanding Hornet avionics), like the MSN PP elevation is 43' as expected.

![image](https://user-images.githubusercontent.com/85649993/142094786-56986ce6-c462-4796-9251-853d35336ea1.png)

**Comment by CaptainBandages** [comment]
Captured from Combatflite export xml it grabs meters and put it into the feet field. It may have been fixed in the latest patch. Haven't really been using it much lately.

**Comment by ilominar** [comment]
Ok, v1.4.1 did fix a ft/m bug in CF imports. Check it out when you get a chance and let me know if it's still broken.

Thanks for the bug report.

**Comment by CaptainBandages** [comment]
No problem. Still such a great tool. Thanks for working on it.

**Comment by ilominar** [comment]
Going to close this. Should have been fixed in v1.4.1.
