### ISSUE TITLE
AV8B Harrier Edit Waypoint function

### ISSUE THREAD

**Issue by MadogPL** [51st-Vfw/DCSWaypointEditor#29]
Could there be an option to not ADD new waypoints in Harrier ( now it goes: add waypoint->77->that creates realistically next waypoint) but EDIT/OVERRIDE them in order?
It make a lot of confusion in combined flights when first waypoint of harrier flight is eight in a row :) (for example)

I'd gladly contribute for this feature to be available.

**Comment by MadogPL** [comment]
Any news on that regard? :)

**Comment by ilominar** [comment]
I haven't been doing much DCSWE development recently due to other demands on my time, so no progress on this unfortunately.

I'm not familiar with the Harrier avionics (I don't own the Harrier), do you have any pointers to the avionics flows for EDIT/OVERRIDE, how the jet responds if you try to edit a waypoint that hasn't been entered (that is, if you start from cold and have no WPs in the system, what happens if you EDIT/OVERRIDE the first SP: does the jet give you a "no such SP" error or just add it as a "new" steer point)? Are you thinking of this as a per-SP or all-SP mode?

Pointers to specific places in documentation I can legally look at (so maybe Chuck's or the official manual?), would be great.

**Comment by MadogPL** [comment]
Hey @ilominar 

I'm really sorry about long wait. 

The only problem I can think of is when you want to add SP/WP 10, and there are for example 5 of them in the system. Then the Harrier will assume you wanted to create WP6. Generally that's why there is this procedure of 77->ENT. 7 is the key closest to ENT button on ODU. You can see this in CHUCK guide on page 426.

https://www.mudspike.com/chucks-guides-dcs-av-8b-harrier-ii/

IF there are 10 SP/WP, and you want to edit 15, and it will do it in sequence - there should be no error. And I don't think that WE is able to create such situation, as it always from 1 to X WP. Not from 1+X to X.

Harrier also has WP0, but I think we can live with that without editing this one to have proper sync with other teams.

**Comment by DarKFeneR996** [comment]
> 

T0 is used as fast target (WPT INC (Waypoint increment) long press will create it while in bombing mode). I don't think u can edit it so easily

**Comment by DarKFeneR996** [comment]
> Hey @ilominar
> 
> I'm really sorry about long wait.
> 
> The only problem I can think of is when you want to add SP/WP 10, and there are for example 5 of them in the system. Then the Harrier will assume you wanted to create WP6. Generally that's why there is this procedure of 77->ENT. 7 is the key closest to ENT button on ODU. You can see this in CHUCK guide on page 426.
> 
> https://www.mudspike.com/chucks-guides-dcs-av-8b-harrier-ii/
> 
> IF there are 10 SP/WP, and you want to edit 15, and it will do it in sequence - there should be no error. And I don't think that WE is able to create such situation, as it always from 1 to X WP. Not from 1+X to X.
> 
> Harrier also has WP0, but I think we can live with that without editing this one to have proper sync with other teams.

Maybe you could input the waypoint you want to start with... like:
I want to rewrite waypoints from waypoint 2 (keeping WPT 1, rewriting over 2, 3, 4 and go on) for every next WPT you want to input

Just a start input

**Comment by MadogPL** [comment]
> > 
> 
> T0 is used as fast target (WPT INC (Waypoint increment) long press will create it while in bombing mode). I don't think u can edit it so easily

Let's not mix things. T0 and W0 are two different things.

**Comment by DarKFeneR996** [comment]
> > > 
> > 
> > T0 is used as fast target (WPT INC (Waypoint increment) long press will create it while in bombing mode). I don't think u can edit it so easily
> 
> Let's not mix things. T0 and W0 are two different things.

I'm sorry x.x

**Comment by MadogPL** [comment]
I'm poking again with this request. :) @ilominar 

Do you need any guide/help in understanding what should be modified? Because all I think you need to do is to add option for harrier to not punch 77->enter, but just type a number from WE.

**Comment by ilominar** [comment]
Ok, this needs to get implemented. I'm embarrassed it's been open so long. Good news is I'm adding it. Bad news is not to DCSWE.

We have a replacement for DCSWE in development based on the DCS-DTC backend with a different native Windows UI and some other UX updates. Viper version is in beta now and a few folks in the 51st are playing with it. Harrier UI for basic waypoints (lat/lon/alt) is done. I just need to port the code that drives DCS from DCSWE to the DCS-DTC way. The repo is not yet visible here but will be eventually.

Right now, DCSWE does the following to enter the waypoints,

```
LMPCD 2
For each waypoint, W
    UFC 7
    UFC 7
    UFC ENT
    ODU 2
    <Enter WP W coords via UFC>
    ODU 1
LMPCD 2
```

As I understand things, the "7-7-ENT" sequence adds the WP to whatever the avionics thinks is the "next" WP slot. From Chuck's, look like you can also do something like this for the core "enter a waypoint" bit:

```
UFC <N-1>
UFC <N>
UFC ENT
ODU 2
<Enter WP coords via UFC with DMS lat/lon>
ODU 1
```

To add the waypoint as waypoint <N> following <N-1>.

If the M waypoints are sequentially numbered from N to N+(M-1), I'm assuming the ask is to be able to select between "7-7-ENT" and "<N-1>-<N>-ENT" sequences for the first three presses?

Also, Can <N> be greater-than 10 (if so, would you then have multiple UFC presses: something like "1-0-1-1-ENT" to enter WP 11 after WP 10? Or is the number always single digit?

 I'm assuming here that the two numbers will be <N> and <N-1> (so something like "3-6-ENT" doesn't make sense?

Finally, are there three buttons in the Harrier cockpit that could be re-purposed for use by the DTC? For example, in the Viper we use some of the FLIR controls that can be pressed but do nothing in the block 50 Viper. Ideally, the Harrier buttons would be push buttons. They would be used to trigger the data load and interact with the app without requiring you to mess with the window.

Thanks for your patience.

**Comment by MadogPL** [comment]
generally - yes :) 

It's not single digit - you enter it like you described 1-1-ENT.

Unfortunately I don't know about any empty buttons. There may be some switches or knobs (for secondary radio) but from what I remember, all buttons are functional.

thank you for your help :) 🥇

**Comment by ilominar** [comment]
This should be in the new thing, see Beta.15 here https://github.com/51st-Vfw/JAFDTC/releases/tag/v1.0.0-B.15

I have yet to do the "free trial" thing to check that it's working, so may be broken, but it's in. Give it a shot.

I'm going to close this out here as further tweaks will be handled through JAFDTC.
