### ISSUE TITLE
MSN import - XML issue

### ISSUE THREAD

**Issue by PieterL1976** [51st-Vfw/DCSWaypointEditor#30]
Hello,

Great job on expanding this!

I'm getting an error when importing a mission package with an CombatFlite (tacview?) XML export.
Could you provide a working mission package that i can use to check my files?

Very simple mission package attached.

- first had a problem with the encoding of the XML export, mine defaulted to UTF-BOM, had to manually convert to UTF using notepad++
- - after that i get this error:
- 
![image](https://user-images.githubusercontent.com/46246478/149880005-bc36ded9-bf51-495e-9866-63b51fab3c97.png)

[Enfield1.zip](https://github.com/51st-Vfw/DCSWaypointEditor/files/7886556/Enfield1.zip)

**Comment by ilominar** [comment]
There are some minor bugs in the mission package path that are now fixed. Before I push the release, would it be possible to get the CombatFlite file you are exporting from? The waypoints in your export don't appear to be tied to any flight.

**Comment by PieterL1976** [comment]
[Files.zip](https://github.com/51st-Vfw/DCSWaypointEditor/files/7896592/Files.zip)
Indeed, ^ this is the CF file + the zip i've created as a mission zip as i believe should be implemented.
From the code i think custom flight names in CF should work as well? Used Enfield1 in this example.
These files give the UTF-BOM error, when i change the encoding to UTF in Notepad++ i get the error as posted above.

**Comment by PieterL1976** [comment]
Hi ilominar, any change of distributing a new build with the edited mission_paclage? I've tried building it myself, but i get all kinds of errors when running the exe.

**Comment by ilominar** [comment]
See v1.5.2.

**Comment by PieterL1976** [comment]
Hi ilominar, small bug in cf_xml.py
line 128, should be  _if dmpi_stn is not None:_ instead of  _if ship is not None:_ 
The code as is gives an error importing MSN dmpi's for multiple ships.

**Comment by ilominar** [comment]
Fixed v1.5.3.
