### ISSUE TITLE
arrow.bin and map.bin missing in the release files

### ISSUE THREAD

**Issue by knightelessar** [51st-Vfw/DCSWaypointEditor#4]
This is important for OpenCV-based DCS F10 map locating and waypoint capturing.
Without the two files, the program will be stuck in capturing.

**Comment by knightelessar** [comment]
Workaround for the user is to copy and paste the two files into the release folder right beside the waypoint editor executable.

**Comment by Viral-51stvfw** [comment]
Should be included in 1.0.0-51stvfw.6 on.  Are you seeing otherwise?

**Comment by knightelessar** [comment]
> Should be included in 1.0.0-51stvfw.6 on. Are you seeing otherwise?

Missing in 
https://github.com/51st-Vfw/DCSWaypointEditor/releases/tag/1.0.0-51stVFW.7

**Comment by Viral-51stvfw** [comment]
Thanks sorry my mistake in the manual build process.

**Comment by knightelessar** [comment]
fixed in 
https://github.com/51st-Vfw/DCSWaypointEditor/releases/tag/v1.0.0-raven_BETA.4
