### ISSUE TITLE
F18 driver not inputting negative elevation value after the minus sign

### ISSUE THREAD

**Issue by knightelessar** [51st-Vfw/DCSWaypointEditor#5]
The capturing of negative elevation coordinates works, but the F18 driver only inputs the minus sign and exits. The actual value auto entering is missing.

**Comment by knightelessar** [comment]
Good for use as a general waypoint with an elevation of zero. However, for precision bombing with the waypoint designated, be aware that the missing elevation value might cause the bombs to hit off the target.

**Comment by Viral-51stvfw** [comment]
Can you attach a profile with an example please.

**Comment by knightelessar** [comment]
![screenshot-1](https://user-images.githubusercontent.com/5753997/123668878-21ccbc80-d86e-11eb-9cb2-ffcc7315ba02.png)
MGRS 40RBP8381621019
-92 feet
F18 waypoint auto-enter coordinates correctly but with elevation zero.

**Comment by CaptainBandages** [comment]
We have the waypoints auto set to zero because it also can create navigation errors especially at higher depths. I think the plan is to have MSN targets take negative values.

**Comment by Viral-51stvfw** [comment]
https://github.com/51st-Vfw/DCSWaypointEditor/blob/7dfd507320da8ddb9f063a3949e275896304515c/src/drivers.py#L176
Was what we changed,  I wasn't able to test the entry though, just the gui.   @knightelessar is stating the entry doesn't complete on its own correct?

**Comment by CaptainBandages** [comment]
Yeah we wanted waypoints to revert to 0' when negative, and MSN targets to input the negative value when over water just in case ED implements a map that has land below sea level.

**Comment by ilominar** [comment]
Probably want to think about how to handle this in the other airframes too---should code be consistent? Current Viper behavior will enter negative elevations, for example.

**Comment by Viral-51stvfw** [comment]
https://github.com/51st-Vfw/DCSWaypointEditor/blob/7dfd507320da8ddb9f063a3949e275896304515c/src/drivers.py#L647
Does this stop the negative entry in the viper?

How does the viper handle target wp if the elevation is "supposed" to be negative? Outside of the code here I mean

**Comment by knightelessar** [comment]
> https://github.com/51st-Vfw/DCSWaypointEditor/blob/7dfd507320da8ddb9f063a3949e275896304515c/src/drivers.py#L647
> 
> 
> Does this stop the negative entry in the viper?
> How does the viper handle target wp if the elevation is "supposed" to be negative? Outside of the code here I mean

No, the code here presses the 0 button to add the negative sign before entering the value.

**Comment by knightelessar** [comment]
Apart from reducing navigation error due to negative elevation, a use case for negative elevation waypoint could be:
1. Vague intel on a CAS/DEAD mission is given as only coordinates with negative elevation for the surface.
2. Ingress and weapon designate waypoint to slave FLIR to visually acquire targets.

The exact negative elevation would yield the closest FLIR sight picture to what is briefed.

**Comment by ilominar** [comment]
Next release will close this as follows:

1. Airframes other than the Hornet and Viper will now clamp <0 elevations to 0 as they do not support negative elevations near as I can tell (only verified for Warthog as I don't have access to other modules, will revisit this as more information comes in).
2. Viper will clamp WPT waypoint elevations to >= -1500', consistent with avionics limits.
3. Hornet will clamp WPT waypoint elevations to >= -2000', consistent with avionics limits.
4. Hornet will clamp MSN waypoint elevations to >= -328', consistent with avionics limits.

Current behaviors for these items,

1. There are no checks for <0 elevations in the non-Hornet/Viper airframes, allowing illegal values.
2. WPT elevations are not clamped, allowing illegal values.
3. WPT elevations are clamped to >= 0.
4. MSN elevations are not clamped, allowing illegal values.

As clamps are applied at the driver, the elevations in the profile database are not constrained.

Negative elevations are mostly an issue with DCS F10 coordinate capture as DCS does not report the elevation of the surface water, but rather, the underlying terrain. The release will add a "clamp to 0" preference for elevations captured from DCS F10.
