### ISSUE TITLE
Error message when importing .xml file generated from CF

### ISSUE THREAD

**Issue by jweneck4009** [51st-Vfw/DCSWaypointEditor#6]
Sample CF strike package created.  Imported to CF, tweaked waypoints and assigned DMPIs.

Import to DCSWPE, and get this error.
Error message pic,  XML file, .miz and .CF files in ZIP

[test2.zip](https://github.com/51st-Vfw/DCSWaypointEditor/files/6729326/test2.zip)
![error](https://user-images.githubusercontent.com/85644593/123705621-350f6600-d835-11eb-997f-82d10318ed2c.PNG)

**Comment by ilominar** [comment]
Thanks. Pulled this up in CF. Looking at Enfield1, I'm assuming the jet should be set up with the following steerpoints (the number is the waypoint number in the CF interface):

1) Departure (WP)
2) Push (WP)
3) Target (WP)
4) AWACS (WP)
5) RTB (WP)
6) Khasab (WP)
7) Sir Abu Nuayr (WP)
8) Truman (WP)

All of these would be "WP" (there are no "MSN" points in this mission).

**Comment by ilominar** [comment]
Should be fixed in v1.0.0-raven_BETA.2

**Comment by jweneck4009** [comment]
There were some dmpis in there for targets…dmpis would be msn
waypoints…dunno if that is possible but long term if it is would be helpful

Josh

**Comment by jweneck4009** [comment]
Avionics and IGM weapons work a little different in the hornet vs
viper…viper uses all waypoints for targets, I’d have to explain it verbally
to show you or I’m sure you already know
