### ISSUE TITLE
DCSWPE Crashes When Hitting the Enter into Jet Button

### ISSUE THREAD

**Issue by jweneck4009** [51st-Vfw/DCSWaypointEditor#7]
DCSWPE Beta 3 crashed when hitting enter into jet.  

Using F18

Tested imported JSON target set, non imported target set, and CF imported coordinate set, and Hitting enter into jet.

Using same import files or non imported target set immidiately with Beta 2 works correctly as is.

Verified results with another party, and they experienced the same.  DSCWPE BETA 3 crashes on enter into jet.  BETA 2 works as designed with same files again,

Attached same exact files that was used successfully in BETA 2.  These files work fine for BETA 2 right after.

 MIZ, JSON export and and Error msg PNG.

[test2.zip](https://github.com/51st-Vfw/DCSWaypointEditor/files/6737218/test2.zip)
[log.txt](https://github.com/51st-Vfw/DCSWaypointEditor/files/6737810/log.txt)

**Comment by knightelessar** [comment]
https://github.com/51st-Vfw/DCSWaypointEditor/releases/tag/v1.0.0-raven_BETA.4
should fix the crash.

**Comment by ilominar** [comment]
Fixed in B4. Root case was unintentional re-use of a method name that was missed when the hotkey code was refactored to be mindful of threading.
