### ISSUE TITLE
Add error for failed coordinates capture

### ISSUE THREAD

**Issue by knightelessar** [51st-Vfw/DCSWaypointEditor#8]
In the event of a capture error, the program errors out, and user data is lost for a temporary coordinate panel. Adding a capture error to allow subsequent capture will enhance the user experience.
Error message:
![image](https://user-images.githubusercontent.com/5753997/124079952-59a94f00-da7c-11eb-8577-470d54f7d82c.png)

User case:
![screenshot-1](https://user-images.githubusercontent.com/5753997/124079991-675ed480-da7c-11eb-93c7-6774991b3d1c.png)

Workaround:
Save the waypoints in a profile. In case of capture error, reopen and reload the previous work.

**Comment by ilominar** [comment]
Cleaning up error handling (and avoiding Python exception dumps) in capture is planned for a future release (a little work has been done in B4 to clean up a few cases). Current plan is to use audio cues to indicate mode, successful capture, and unsuccessful capture to align with the design goal of limiting back-and-forth between DCS and DCSWE and still provide feedback on what is going on.

**Comment by knightelessar** [comment]
This issue can be closed because the user pain is solved by the introduction of audio cues to capture success and failure in https://github.com/51st-Vfw/DCSWaypointEditor/releases/tag/v1.0.0-raven_BETA.6
