### ISSUE TITLE
Add save feature for current named profile

### ISSUE THREAD

**Issue by knightelessar** [51st-Vfw/DCSWaypointEditor#9]
Currently, for a named profile there is only the save as option, and updating an existing profile is hard. Making the save as button into save will make the updating easier. Maybe the save as option is already included in the file export options.

**Comment by ilominar** [comment]
Agreed, persistence is wonky. Considering a few thins, but will likely start to track clean/dirty state of the profile and use save/save_as/revert/delete verbs for profiles that are available based on clean/dirty state. This is more in line with UX expectations than the implementation we forked from.

**Comment by ilominar** [comment]
B5 changes up profile model. Should be easier to update existing profiles with the new UX.

**Comment by knightelessar** [comment]
Menu bar > profile > save feature is added in https://github.com/51st-Vfw/DCSWaypointEditor/releases/tag/v1.0.0-raven_BETA.6
